Working Code

In [1]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils
from sklearn import metrics
import numpy as np

Using TensorFlow backend.


In [2]:
#load train csv file and convert to values
#changed string value to numeric
#'Iris-setosa' to 0
#'Iris-versicolor' to 1
#'Iris-virginica' to 2

xls = pd.ExcelFile('C:/Users/Amit/Desktop/Embedded Vision 2/lab 3/iris_train.csv')
datatrain = pd.read_excel(xls, 'Sheet1')
datatrain.values

datatrain = datatrain.apply(pd.to_numeric)

#change dataframe to array
datatrain_array = datatrain.as_matrix()

#split x and y (feature and target)
xtrain = datatrain_array[:,:4]
ytrain = datatrain_array[:,4]


In [3]:
#load test data
xls = pd.ExcelFile('C:/Users/Amit/Desktop/Embedded Vision 2/lab 3/iris_test.csv')
datatest = pd.read_excel(xls, 'Sheet1')
datatest.values

datatest = datatest.apply(pd.to_numeric)

#change dataframe to array
datatest_array = datatest.as_matrix()

#split x and y (feature and target)
xtest = datatest_array[:,:4]
ytest = datatest_array[:,4]

In [4]:
#change target format
ytrain = np_utils.to_categorical(ytrain)

In [5]:

# create model
model = Sequential()
model.add(Dense(8, input_dim=4, activation='sigmoid'))
model.add(Dense(3, activation='sigmoid'))


In [6]:
#choose optimizer and loss function
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

#train the model
model.fit(xtrain, ytrain, epochs=20, batch_size=120)

#get weights
Weights_IH = model.layers[0].get_weights()[0]
Weights_HO = model.layers[1].get_weights()[0]

print('INPUT-HIDDEN LAYER WEIGHTS:')
print(Weights_IH)
print('HIDDEN-OUTPUT LAYER WEIGHTS:')
print(Weights_HO)

Epoch 1/20
120/120 [==============================] - 0s - loss: 1.1398 - acc: 0.3083
Epoch 2/20
120/120 [==============================] - 0s - loss: 1.1396 - acc: 0.3083
Epoch 3/20
120/120 [==============================] - 0s - loss: 1.1394 - acc: 0.3083
Epoch 4/20
120/120 [==============================] - 0s - loss: 1.1392 - acc: 0.3083
Epoch 5/20
120/120 [==============================] - 0s - loss: 1.1389 - acc: 0.3083
Epoch 6/20
120/120 [==============================] - 0s - loss: 1.1387 - acc: 0.3083
Epoch 7/20
120/120 [==============================] - 0s - loss: 1.1385 - acc: 0.3083
Epoch 8/20
120/120 [==============================] - 0s - loss: 1.1382 - acc: 0.3083
Epoch 9/20
120/120 [==============================] - 0s - loss: 1.1380 - acc: 0.3083
Epoch 10/20
120/120 [==============================] - 0s - loss: 1.1378 - acc: 0.3083
Epoch 11/20
120/120 [==============================] - 0s - loss: 1.1376 - acc: 0.3083
Epoch 12/20
120/120 [==============================]

In [7]:
# Get prediction
yPred = model.predict_classes(xtest, batch_size=120)
print("\nprediction is :",yPred)

# Print Confusion Matrix and accuracy
cm=np.asarray(metrics.confusion_matrix(yPred,ytest))
cm=cm.reshape(3,3)
print("Confusion matrix: \n" ,cm)
print("accuracy is: %s " % metrics.accuracy_score(yPred,ytest))

30/30 [==============================] - 0s

prediction is : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Confusion matrix: 
 [[13  6 11]
 [ 0  0  0]
 [ 0  0  0]]
accuracy is: 0.433333333333 
